# Pipeline name
name: Deploy Website

# Set permission to merge the pr
permissions: write-all

# When pipeline is triggered
on:
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  # Deploy job
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      # Deploy code to Netlify
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  # Automerge job
  automerge:
    # Execute only if deploy job succeeds
    needs:
      - deploy
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      - name: Automerge
        uses: "micheletriaca/automerge-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""